# Import all types and queries
#import types/User.graphql
#import types/Company.graphql
#import types/CompanyMeta.graphql
#import types/Checklistable.graphql
#import types/Checklist.graphql
#import types/PlanMeta.graphql
#import types/Invoice.graphql
#import types/Plan.graphql
#import types/Customer.graphql
#import types/Item.graphql
#import types/Discount.graphql
#import types/Tax.graphql
#import types/Reminder.graphql
#import types/Link.graphql
#import types/Charity.graphql
#import types/CompanyMailSetting.graphql
#import inputs/InvoiceInput.graphql
#import inputs/CompanyInput.graphql
#import queries/Query.graphql
#import mutations/Mutation.graphql


scalar DateTime @scalar(class: "Nuwave\\Lighthouse\\Schema\\Types\\Scalars\\DateTime")
scalar JSON @scalar(class: "MLL\\GraphQLScalars\\JSON")
scalar Upload @scalar(class: "Nuwave\\Lighthouse\\Schema\\Types\\Scalars\\Upload")